---
github_actions:
    - ".github/**"
dev_container:
    - ".devcontainer/**"
config:
    - ".*"
    - "*.js"
    - "*.json"
    - "*.toml"
    - "*.yaml"
    - "*.yml"
documentation:
    - "**.md"
    - "docs/**"
    - LICENSE
python:
    - "src/**"
    - "tests/**"
dependencies:
    - "*.lock"
